import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data, isLoading } = api.esi.OAuthURL.useQuery();
  if (isLoading) {
    return <div>Loading...</div>;
  }
  if (!data) {
    return <div>Sominthing Wrong</div>;
  }
  const { url: authURL, state: state } = data;

  console.log("authURL::: ", authURL);
  console.log("state::: ", state);

  localStorage.setItem("state", state);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <a href={authURL}>
          <img
            src="https://web.ccpgamescdn.com/eveonlineassets/developers/eve-sso-login-white-small.png"
            alt="EVE SSO Login Buttons Small White"
          />
        </a>
      </main>
    </>
  );
};

export default Home;
